language: generic

dist: xenial

sudo: required

services:
  - docker

notifications:
  email: false

env:
  - OTP_VERSION=22.2.1 ELIXIR_VERSION=1.9.4

cache:
  directories:
    - /home/travis/cache/docker-otp-22.2.1-elixir-1.9.4
    - test/cavp_SUITE_data/186-3rsatestvectors
    - test/cavp_SUITE_data/aesmmt
    - test/cavp_SUITE_data/archive
    - test/cavp_SUITE_data/gcmtestvectors
    - test/cavp_SUITE_data/keccaktestvectors
    - test/cavp_SUITE_data/kwtestvectors
    - test/cavp_SUITE_data/pkcs-1v2-1-vec

before_install:
  - rm -rf ./docker-otp-${OTP_VERSION}-elixir-${ELIXIR_VERSION}
  - mkdir -p /home/travis/cache/docker-otp-${OTP_VERSION}-elixir-${ELIXIR_VERSION}
  - ln -svf /home/travis/cache/docker-otp-${OTP_VERSION}-elixir-${ELIXIR_VERSION} ./docker-otp-${OTP_VERSION}-elixir-${ELIXIR_VERSION}
  - make docker-setup DOCKER_OTP_VERSION=${OTP_VERSION} DOCKER_ELIXIR_VERSION=${ELIXIR_VERSION}

script:
  - make docker-test DOCKER_OTP_VERSION=${OTP_VERSION} DOCKER_ELIXIR_VERSION=${ELIXIR_VERSION}
